spring:
  config:
    active:
      on-profile: local

  datasource:
    url: jdbc:mysql://localhost:3306/ollsyDB
    username: root
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver


  h2:
    console:
      enabled: false
      path: /h2-console