spring:
  config:
    active:
      on-profile: local

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test   # (In-Memory Mode)
    username: sa        # H2 DB  ID
    password:         # H2 DB  PW


  h2:
    console:
      enabled: true
      path: /h2-console