server:
  port: 80

spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: 'jdbc:h2:mem:test'   # (In-Memory Mode)
    #url: 'jdbc:h2:~/test'    #  (Embedded Mode)
    username: sa        # H2 DB  ID (??? ??)
    password:         # H2 DB  PW (??? ??)

  # H2 Console ??
  h2:
    console:
      enabled: true
      path: /h2-console


  logging:
    level:
      org.hibernate.orm.jdbc.bind: TRACE

  spring:
    jpa:
      show-sql: true
      properties:
        hibernate:
          format_sql: true
          use_sql_comments: true
          highlight_sql: true

      hibernate:
        ddl-auto: create